class CONFIG:
    MINIMUM_NAME_LENGTH = 3
    MAXIMUM_NAME_LENGTH = 50
    IMAGE_EXTENSIONS = ["png", "jpg"]
    MINIMUM_PICTURE_SIZE = 5000
    MAXIMUM_PICTURE_SIZE = 20485760
    UPLOAD_DIRECTORY = "maps"
    MINIMUM_IMAGE_WIDTH = 100
    MINIMUM_IMAGE_HEIGHT = 100
    THUMBNAIL_SIZE = 512
    THUMBNAIL_DIRECTORY = UPLOAD_DIRECTORY + "/thumbnails"
    MAPS_PER_PAGE = 100
