class CONFIG:
    MINIMUM_NAME_LENGTH = 3
    MAXIMUM_NAME_LENGTH = 50
    IMAGE_EXTENSIONS = ["png", "jpg"]
    MINIMUM_IMAGE_SIZE_IN_BYTES = 5000
    MAXIMUM_IMAGE_SIZE_IN_BYTES = 20485760
    UPLOAD_DIRECTORY = "maps"
    MINIMUM_IMAGE_DIMENSION = 100
    THUMBNAIL_SIZE = 512
    THUMBNAIL_DIRECTORY = UPLOAD_DIRECTORY + "/thumbnails"
    MAPS_PER_PAGE = 100
